package za.ac.iie.opsc_poe_screens

import java.util.Date

/**
 * Data models for the application, configured for Firebase Realtime Database.
 * Key requirements:
 * 1. Must have a public no-argument constructor (auto-generated by Kotlin if all properties have defaults).
 * 2. All properties that will be read from the database must be 'var'.
 */

data class User(
    var uid: String = "",
    var username: String = "",
    var password: String = ""
)

data class Account(
    var id: String = "",
    var accountName: String = "",
    var colour: Int = 0,
    // NEW: The maximum spending limit for this account per month.
    // Set during account creation. A value of 0.0 means no limit.
    var maxMonthlySpend: Double = 0.0
)

data class Category(
    var id: String = "",
    var name: String = "",
    var iconId: Int = 0,
    var isIncome: Boolean = false
)

data class Goal(
    var id: String = "",
    var goalName: String = "",
    var description: String = "",
    var amount: Double = 0.0, // The target amount (e.g., spend less than 1000, or save 500)

    // NEW: The ID of the account this goal is linked to. This is crucial.
    var accountId: String = "",

    // NEW: Defines the type of goal. "SPENDING" or "SAVINGS".
    var goalType: String = GoalType.SPENDING.name,

    // NEW: The specific month and year this goal applies to (e.g., "2025-11").
    // This allows for historical tracking and resetting goals each month.
    var monthYear: String = "",

    // This is no longer entered by the user, but calculated by your app.
    var currentAmount: Double = 0.0,
    var completed: Boolean = false,
    var bonus: Boolean = false
)

// NEW: An Enum to define the types of goals. This prevents typos and makes code clearer.
enum class GoalType {
    SPENDING, // Tracks expenses
    SAVINGS,  // Tracks income
}

data class ImageItem(
    var id: String = "",
    var storageUrl: String = "",
    var imageTitle: String = ""
)

data class FinancialTransaction(
    var id: String = "",
    var amount: Double = 0.0,
    var description: String = "",
    var accountId: String = "",
    var categoryId: String = "",
    var isRecurring: Boolean = false,
    var date: Date = Date(),
    var receiptUrl: String? = null
)

/**
 * This is a helper class used within the app's logic (ViewModel/UI).
 * It doesn't need to be stored in the database, so it can have 'val' properties.
 * It's perfectly fine as is.
 */
data class TransactionDetails(
    val transaction: FinancialTransaction,
    val account: Account,
    val category: Category?
)

data class AccountWithBalance(
    val account: Account,
    val balance: Double, // calculate this in the ViewModel
    val income: Double,
    val expenses: Double
)